### ISSUE TITLE
Is this really necessary? :)

### ISSUE THREAD

**Issue by nul800sebastiaan** [akuryan/LetsEncrypt.Umbraco#1]
Have you tried the other option of adding the following to web.config, which is much less work (in `system.webServer/rewrite/rules`):

```
    <rule name="AcmeChallenge" patternSyntax="Wildcard">
      <match url=".well-known/acme-challenge*" />
      <action type="Rewrite" url="{R:0}/index.html" />
    </rule>
```

**Comment by akuryan** [comment]
But, if I get this right, it will require me to move verification file manually to index.html, is not it? So, it means, that once in 90 days it will require manual action... It is OK if you have one web app, but if you have dozen of them?

**Comment by nul800sebastiaan** [comment]
I'm not sure what you mean? What is it exactly that you do now?

**Comment by akuryan** [comment]
Currently, I used code to check, if there is a file in .well-known folder and serve it as a static file. Rewrite rule you are proposing (if I get it right) - will redirect all request to index.html

Let's Encrypt in Azure wep app creates a check files

So, to verify my web app, it will request this file
curl http://_web_app_url_/.well-known/acme-challenge/UtxCs7-lA4m-zkK-HdS7h0YwNrQRQS5s4h2vuwjKp08

Rewrite solution requires me to move UtxCs7-lA4m-zkK-HdS7h0YwNrQRQS5s4h2vuwjKp08 to index.html manually.
Owin startup solution does not requires me to do anything manually, allowing automatic verification once in 90 days - so, despite of slight overhead it adds, it is much more profitable IMHO. Do not you agree?

**Comment by akuryan** [comment]
Also, I checked rewrite solution - for me it does not work :( It redirects and returns error 500

**Comment by nul800sebastiaan** [comment]
>  if there is a file in .well-known folder and serve it as a static file

so what kind of a file is this? and how do you update it's content?

**Comment by akuryan** [comment]
Yes, there is a file, but it is generated as extensionless file, and, as described here - https://www.jdibble.co.uk/blog/using-letsencrypt-with-umbraco - Umbraco intercepts extensionless requests and tries to map them to Umbraco items. And finally, it generates 404 instead of trying to serve a file.

File is generated automatically along with a content by Let's Encrypt extension for Azure web app

**Comment by nul800sebastiaan** [comment]
Ah alright then. Yeah, I create it differently, I actually create `http://web_app_url/.well-known/acme-challenge/UtxCs7-lA4m-zkK-HdS7h0YwNrQRQS5s4h2vuwjKp08/index,html`.

Alrighty then, this seems to be useful for people then! Issue closed.
